version: '3.7'

services:
  angular-app:
    image: mohamedamineboughrara/angular-app:latest
    ports:
      - 82:82
    depends_on:
      - demo-app

  demo-db:
    container_name: demo-db
    image: postgres:latest
    networks:
      - demo-network
    environment:
      - POSTGRES_USER=new_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo-db
    volumes:
      - dbvol:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

  demo-app:
    build:
      context: .
    container_name: demo-spring
    image: mohamedamineboughrara/demo:latest
    ports:
      - "8089:8089"
    depends_on:
      - demo-db
    environment:
      - POSTGRES_HOST=demo-db
      - POSTGRES_USER=new_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo
      - POSTGRES_PORT=5433
    networks:
      - demo-network
    volumes:
      - dbvol:/var/lib/postgresql/data

networks:
  demo-network:
    driver: bridge

volumes:
  dbvol:

