version: '3.7'
services:
  
  angular-app:
    image: mohamedamineboughrara/angular-app:latest
    ports:
      - 4200:4200
    depends_on:
      - app

  demo-db:
    container_name: demo-db
    image: postgres:latesr
    networks:
      - demo-network
    environment:
      - POSTGRES_USER=new_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=achatdb

    volumes:
      - dbvol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
     demo-app:
    build:
      context: .
    container_name: demo-spring
    image: mohamedamineboughrara/demo:latest
    ports:
      - "8081:8081"
    networks:
      - demo-network
    depends_on:
      - demo-db
    environment:
      - POSTGRES_HOST=demo-db
      - POSTGRES_USER=new_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo
      - POSTGRES_PORT=5432
     networks:
       tpachat-network:
        name: demo-network

     volumes:
       dbvol:
      
     
    
